### ISSUE TITLE
Adding more automation features

### ISSUE THREAD

**Issue by ChristianKuehnel** [flecmart/keep2todoist#19]
Hi @flecmart,

Thank you for building this tool, this is really useful!

I'm also using Alexa (in parallel to the Google Asisstant) to create tasks in Todoist, however the [Alexa integration](https://todoist.com/help/articles/use-amazon-alexa-with-todoist) creates the tasks in a separate projects in Todoist which is really annoying. So I've created a little tool that can move and update tasks based on a few simple rules: https://github.com/ChristianKuehnel/todoistautomation 

This solves my use case for Alexa, but can but used to modify any tasks that match a filter query automatically.

The idea is based on what you're doing with keep2todoist and the architecture is quite similar. Do you think it would make sense to merge both tools? 

Best,
Christian

**Comment by flecmart** [comment]
Hi Christian,

Generally I am open to PRs, extending this tool but thinking about this particular case I am not 100% convinced it is a good idea.

Not that I don't like your idea, let me explain my thought process:

This tool mainly aims for the Google assistant integration and I want it to be as easy as possible to use and accessible for everyone. That is why I spent some time in implementing config validation so it is kind of fool proof and I don't have to spent too much time in supporting users that didn't use yaml before. I think this gets complex pretty fast the more features are added plus more automation features would also affect the scheduling. Right now, I think there is a need for an easy to use tool like this because todoist now  stopped their google assistant integration completely.

For now, I am happy to link to your project in the Readme for Alexa users? If you have good ideas on how to integrate your automation features optionally, without breaking the validation and generally not increasing complexity of config and scheduling too much, I would review this, but currently my spare time is too limited to evaluate and implement this myself.

**Comment by ChristianKuehnel** [comment]
Hi flecmart,

Yeah, I also wasn't 100% sure if merging the tools would make sense, but I
wanted to ask anyway.. I also don't have much time for the maintenance, so
let's keep them separate and just point to the other solution via
documentation.

If you ever see the need for something in the direction of Alexa support or
some automation rules, feel free to ping me.

Best,
Christian


Am So., 5. Feb. 2023 um 20:01 Uhr schrieb flecmart ***@***.***
