### ISSUE TITLE
BadAuthentication

### ISSUE THREAD

**Issue by khaberz** [flecmart/keep2todoist#29]
I don't exactly know when it stopped working - there was a Debian Upgrade in that time which is a possible reason. I do get the following error now, which I can't figure out. Any Help is much appreciated. And thank you for this immensely helpful tool!

`
2023-06-15 14:27:37 configManager-INFO: validating configuration with schema './config.schema.yaml'

2023-06-15 14:27:37 configManager-INFO: schema validation passed 👍

2023-06-15 14:27:37 configManager-INFO: configuration validation passed 👍

2023-06-15 14:27:37 configManager-INFO: updated config: config.yaml

Traceback (most recent call last):
  File "/home/khaberz/keep2todoist-main/app/app.py", line 152, in <module>
    keep.login(configManager.config['google_username'], configManager.config['google_password'], device_id='3ee9002270d00157')
  File "/home/khaberz/keep2todoist-main/venv/lib/python3.11/site-packages/gkeepapi/__init__.py", line 697, in login
    ret = auth.login(email, password, device_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khaberz/keep2todoist-main/venv/lib/python3.11/site-packages/gkeepapi/__init__.py", line 62, in login
    raise exception.LoginException(res.get("Error"), res.get("ErrorDetail"))
gkeepapi.exception.LoginException: ('BadAuthentication', None)`

**Comment by flecmart** [comment]
Hey,

I did not notice any changes in the authentication process for gkeepapi. Did you eventually enable 2FA recently, or changed your Google password? I would check the app password, maybe generate and try a new one.

**Comment by khaberz** [comment]
Thanks for your response. I have always has 2FA running, and that hasn't been a problem before. I have already tried a new app password as I had suspected something in there as well. 
As part of the Debian-Upgrade I had to re-install the modules in the venv I have set up for this. Do you think any of those could cause the propblem?
Thanks so much again!

**Comment by flecmart** [comment]
Hm, I guess it could be but it is hard to debug remotely. Are you able to
try using the prebuilt docker image? This one ia always tested that all
dependencies work together.

khaberz ***@***.***> schrieb am Fr., 16. Juni 2023, 09:44:

**Comment by sekrause** [comment]
I think this is triggered by the following bug, `gpsoauth` doesn't seem to be working correctly with OpenSSL 3: https://github.com/simon-weber/gpsoauth/issues/48

That's why @khaberz had started having this problem after upgrading Debian: Bullseye uses OpenSSL 1.1.1, but Debian Bookworm ships OpenSSL 3.

The Docker container should be fine _for now_ since it was last rebuilt two months ago with Bullseye, but the `Dockerfile` depends on `python:3.9` which is now based on Bookworm. So the Docker container could have the same problem after the next rebuild. I think it might be a good idea so change the line `FROM python:3.9` to `FROM python:3.9-bullseye` in the `Dockerfile` to stay on Bullseye as long as the OpenSSL 3 problem exists.

**Comment by khaberz** [comment]
Thanks @flecmart - The prebuilt Docker image works (after a small modification on calling the config.yaml, so in my case _docker run -v **/home/khaberz/k2t/keep2todoist-1.3.1/app/**config.yaml:/app/config.yaml --restart always ghcr.io/flecmart/keep2todoist:latest_ - thanks @sekrause )

**Comment by flecmart** [comment]
Closed by #30 - thank you!

**Comment by marothe** [comment]
@flecmart 
someone got a different idea, getting the same error:

```
2024-08-27 19:20:40 configManager-INFO: validating configuration with schema './config.schema.yaml'
2024-08-27 19:20:40 configManager-INFO: validation passed 👍
2024-08-27 19:20:40 configManager-INFO: updated config: config.yaml
Traceback (most recent call last):
  File "/app/./app.py", line 154, in <module>
    keep.login(configManager.config['google_username'], configManager.config['google_password'], device_id='3ee9002270d00157')
  File "/usr/local/lib/python3.9/site-packages/gkeepapi/__init__.py", line 697, in login
    ret = auth.login(email, password, device_id)
  File "/usr/local/lib/python3.9/site-packages/gkeepapi/__init__.py", line 62, in login
    raise exception.LoginException(res.get("Error"), res.get("ErrorDetail"))
gkeepapi.exception.LoginException: ('BadAuthentication', None)
```

this is my config: 

```
update_interval_s: 60
google_username: google_username
google_password: app_password
todoist_api_token: api_token
healthcheck: # optional: configure some kind of healtcheck endpoint providing service monitoring, e.g. https://healthchecks.io/
  url: https://hc-ping.com/uuid
  period_min: 240
keep_lists:  # list your keep lists on this level
  - Einkaufsliste:
      sync_labels: false
      todoist_project: 'Einkaufsliste' # optional: you can choose a project for todoist here
```


I had this running without error but moved SSDs for my docker-compose install, so I rebuilt this (docker-build). 

Getting this error now, I already tried:

- reinstalling it again, prune all the images and trying again
- changing my google app password
- changed the dependency to `python:3.9-bullseye` 

any ideas?

**Comment by flecmart** [comment]
Hmm, did you usse the original docker-compose and Dockerfile from this repo? I did not rebuild myself for some time so it could be that some underlying dependency changes broke this... Unfortunately I don't have any spare time at the mooment because I have a lot going on with family.

https://github.com/flecmart/keep2todoist/issues/57 Here I collected what config worked for me in the past.

Meanwhile there were also updates to gpsoauth and gkeepapi as a lot of users had the same problems. See the open pull requests.

Some info on the alternative approach here: https://github.com/simon-weber/gpsoauth?tab=readme-ov-file#alternative-flow Last time when I read through I thought it was not as intuitive and easy as the current working flow, but I think at some point I need to upgrade those dependencies and test it myself. But at the moment I have no time... if you or anyone have the resources and skills to implement those changes I am happy to review and merge it - more I cannot do at the moment.

**Comment by marothe** [comment]
@flecmart sorry for the late reply here, my server crashed in the meantime and I also only now got everything back up again. I saw you have a new draft PR with the new auth. approach, will try this once this is merged! (tried it right now and still got an error, even with the new master token) - thank you so much for keep working on this!
